sudo: required
services:
  - docker

before_install:
  - docker build -t devsanghvi/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true devsanghvi/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker"
  env: "Docker-env"
  bucker_name: "elasticbeanstalk-us-east-2-883144076464/?region=us-east-2&tab=overview"
  bucket_path: "docker"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"